from enum import Enum


class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    FAILED = "FAILED"
    CAPTURED = "CAPTURED"
    REFUNDED = "REFUNDED"


class PaymentMethod(str, Enum):
    UPI = "UPI"
    CARD = "CARD"
    NETBANKING = "NETBANKING"
    WALLET = "WALLET"


class RecoveryState(str, Enum):
    AT_RISK = "AT_RISK"
    ANALYZING = "ANALYZING"
    RECOMMENDED = "RECOMMENDED"
    SAFETY_CHECK = "SAFETY_CHECK"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    RECOVERED = "RECOVERED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    STOPPED = "STOPPED"
    EXPIRED = "EXPIRED"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class RecoveryActionType(str, Enum):
    DELAYED_RETRY = "DELAYED_RETRY"
    IMMEDIATE_RETRY = "IMMEDIATE_RETRY"
    PAYMENT_LINK = "PAYMENT_LINK"
    CUSTOMER_NOTIFICATION = "CUSTOMER_NOTIFICATION"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    STOP_RECOVERY = "STOP_RECOVERY"


class PolicyDecisionType(str, Enum):
    ALLOW = "ALLOW"
    REQUIRE_HUMAN_APPROVAL = "REQUIRE_HUMAN_APPROVAL"
    BLOCK = "BLOCK"


class ActionExecutionStatus(str, Enum):
    PENDING = "PENDING"
    EXECUTED = "EXECUTED"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AuditActor(str, Enum):
    AGENT = "AGENT"
    POLICY_ENGINE = "POLICY_ENGINE"
    HUMAN_OPERATOR = "HUMAN_OPERATOR"
    SIMULATOR = "SIMULATOR"
    WEBHOOK = "WEBHOOK"
    SYSTEM = "SYSTEM"


class AuditEventType(str, Enum):
    PAYMENT_FAILED = "PAYMENT_FAILED"
    RISK_DETECTED = "RISK_DETECTED"
    AI_ANALYSIS = "AI_ANALYSIS"
    AI_RECOMMENDATION = "AI_RECOMMENDATION"
    POLICY_APPROVED = "POLICY_APPROVED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    HUMAN_APPROVAL_REQUESTED = "HUMAN_APPROVAL_REQUESTED"
    HUMAN_APPROVED = "HUMAN_APPROVED"
    HUMAN_REJECTED = "HUMAN_REJECTED"
    ACTION_EXECUTED = "ACTION_EXECUTED"
    ACTION_BLOCKED = "ACTION_BLOCKED"
    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    RECOVERY_SUCCESS = "RECOVERY_SUCCESS"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    RECOVERY_STOPPED = "RECOVERY_STOPPED"
    SETTINGS_UPDATED = "SETTINGS_UPDATED"
